{
    /* TODO: https://github.com/JetBrains/Grammar-Kit/tree/master/resources/messages/attributeDescriptions */
    parserClass="ru.nim.parser.NimParser"

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Nim"
    psiImplClassSuffix="Impl"
    psiPackage="ru.nim.psi"
    psiImplPackage="ru.nim.psi.impl"

    elementTypeHolderClass="ru.nim.psi.NimTypes"
    elementTypeClass="ru.nim.psi.NimElementType"
    tokenTypeClass="ru.nim.psi.NimTokenType"
}

//nimFile ::= (proc|COMMENT|NEW_LINE)*
nimFile ::= (proc|COMMENT|BLOCK_COMMENT|NEW_LINE|STR_LIT|TRIPLESTR_LIT|RSTR_LIT|HEX_LIT|DEC_LIT|OCT_LIT|BIN_LIT
            |INT8_LIT|INT16_LIT|INT32_LIT|INT64_LIT|UINT_LIT|UINT8_LIT|UINT16_LIT|UINT32_LIT|UINT64_LIT|FLOAT_LIT
            |FLOAT32_LIT|FLOAT64_LIT)*

// Just for test
proc ::= KW_PROC ":"
//proc ::= KW_PROC IDENTIFIER ":" NEW_LINE? STR_LIT